name: AFFiNE
version: "2.1.1"
slug: affine
description: Run AFFiNE as Home Assistant Add-On
url: "https://github.com/danez/hassio-addons/tree/main/affine"
hassio_api: true
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: False
    path: /root/.affine/config
  - type: share
    read_only: False
ports:
  3010/tcp: 3010
ports_description:
  3010/tcp: Web interface
options:
  LOG_LEVEL: "warning"
  DB_USERNAME: "affine"
  DB_PORT: 5432
  DB_DATABASE_NAME: "affine"
schema:
  LOG_LEVEL: "str?"
  DB_USERNAME: "str"
  DB_PASSWORD: "password"
  DB_HOSTNAME: "str"
  DB_PORT: "port"
  DB_DATABASE_NAME: "str"
  TURNSTILE_SITE_KEY: "str?"
image: "ghcr.io/danez/{arch}-addon-affine"
